--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-eks-cluster
  region: eu-west-2
  version: "1.28"
availabilityZones:
- eu-west-2a
- eu-west-2b
managedNodeGroups:
- name: simple-node
  instanceType: t3.small
  desiredCapacity: 1
- name: simple-node2
  instanceType: t3.small
  desiredCapacity: 1

