
apiVersion: v1
kind: Service
metadata:
  name: java-svc
spec:
  selector:
    app: java-ui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32294
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-ui
  name: java-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-ui
  template:
    metadata:
      labels:
        app: java-ui
    spec:
      containers:
      - image: 669016063732.dkr.ecr.eu-west-2.amazonaws.com/simple-java-app
        imagePullPolicy: IfNotPresent
        name: simple-java-app
       
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: java-configmap
              key: database_host
        
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: java-configmap
              key: database_port

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: java-secret
              key: database_password

            
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: java-configmap
              key: database_user

        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: java-configmap
              key: database

        ports:
        - containerPort: 8080

  

